#This is a Dockerfile which includes normal users with normal privilledges.
FROM centos:latest

MAINTAINER yogeshgavhane596@gmail.com
RUN useradd -ms /bin/bash test
CMD echo "Hello this is Yogesh Gavhane and this is a test CMD for docker build process."
USER test
